[build]
builder = "RAILPACK"
cmd = '''
cd frontend
npm install
npm run build
cd ..
cd backend
go mod tidy
go build -o main .
'''

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
useLegacyStacker = false
multiRegionConfig = { "europe-west4-drams3a" = { numReplicas = 1 } }
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[start]
cmd = "cd backend && ./main"