[build]
builder = "Nixpacks"

[build.backend]
dir = "backend"
buildCommand = "cd backend && go mod tidy && go build -o main ."

[build.frontend]
dir = "frontend"
buildCommand = "cd frontend && npm install && npm run build"
publish = "frontend/dist"

[deploy]
startCommand = "cd backend && ./main"

[[services]]
name = "web"
port = 8080